/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/** An update ready to download and install. */
export declare class AvailableUpdate {
  /** Version currently running. */
  get currentVersion(): string
  /** Version announced by the feed. */
  get version(): string
  /** Release notes, if the feed sent `notes`. */
  get notes(): string | null
  /** RFC 3339 publish date, if the feed sent `pub_date`. */
  get date(): string | null
  /** Download URL from the feed. */
  get downloadUrl(): string
  /** Packager format: `app`, `appimage`, `nsis`, or `wix`. */
  get format(): string
  /**
   * Download, verify the signature, and replace the running app.
   *
   * Does not relaunch. Quit after this returns, or the next start uses the
   * new files.
   */
  downloadAndInstall(): Promise<unknown>
}

/** The main GPUI renderer exposed to Node.js. */
export declare class GpuixRenderer {
  /**
   * Highlight code in JavaScript: `callback` gets each code block missing
   * from the syntax cache, and answers through [`Self::answer_highlight`].
   */
  onHighlight(callback: ((err: Error | null, arg: HighlightRequest) => any)): void
  /**
   * Answer highlight request `id`. `spans` holds `[start, end, kind]`
   * triples: UTF-8 byte ranges into the request's code, and indices into
   * `kinds`, which names `HighlightKind`s in camelCase. `null` spans mean
   * the code can't be highlighted.
   */
  answerHighlight(id: number, kinds: Array<string>, spans?: Uint32Array | undefined | null): void
  constructor(eventCallback?: (((err: Error | null, arg: EventPayload) => any)) | undefined | null)
  /** Initialize GPUI using the native event-loop architecture for this OS. */
  init(options?: WindowOptions | undefined | null): void
  /**
   * Apply a batch of mutations in a single FFI call.
   *
   * Accepts a JSON array of mutation tuples. Each tuple is an array where
   * the first element is the operation name (string) and remaining elements
   * are the arguments:
   *
   *   ["createElement",    id, "type"]
   *   ["destroyElement",   id]
   *   ["appendChild",      parentId, childId]
   *   ["insertBefore",     parentId, childId, beforeId]
   *   ["setStyle",         id, { ...style }]
   *   ["setText",          id, "content"]
   *   ["setEventListener", id, "eventType", true|false]
   *   ["setRoot",          id]
   *   ["setKeyboardFocusDim", true|false]
   *   ["setCustomProp",    id, "key", value]
   *
   * Returns accumulated destroyed IDs from all destroyElement ops.
   * Acquires the tree mutex ONCE for the entire batch.
   */
  applyBatch(json: string): Array<number>
  /** Pump the native event loop. Returns false after the last window closes. */
  tick(): boolean
  isInitialized(): boolean
  /**
   * Whether JavaScript must call tick() until it returns false.
   *
   * macOS: tick() pumps AppKit. Windows/Linux: tick() only reports whether
   * the UI thread is still inside `Platform::run`. Both return false after
   * the last window closes so the JS frame loop can exit the process.
   */
  requiresTick(): boolean
  /**
   * The paintable size of the window in logical pixels, excluding any
   * platform title bar. This used to answer a hardcoded 800x600, so anything
   * that turned a mouse position into layout coordinates pointed at the
   * wrong place on every window that was not exactly that size.
   */
  getWindowSize(): WindowSize
  /**
   * Maximized, fullscreen, active and dark, plus the size, as of the last
   * frame. Never waits on the window, so it is safe to poll and still
   * answers after the window closed.
   */
  getWindowState(): WindowState
  getWindowInsets(): WindowInsets
  /** `"hidden"` | `"minimal"` | `"full"`. Paints into the scene after layout. */
  setDebugFrameOverlay(mode: string): string
  /** Hidden → minimal → full → hidden. */
  cycleDebugFrameOverlay(): string
  getDebugFrameOverlay(): string
  /** Clears the last 1000 draw samples. Frame count stays. */
  resetDebugFrameOverlayStats(): void
  /** Same numbers as the on-screen overlay: current, p90, p99, max, frames. */
  getDebugFrameOverlayStats(): DebugFrameOverlayStats
  /**
   * Bring the window forward and give it focus. This is how a window opened
   * with `show: false` or `focus: false` is revealed later.
   */
  activateWindow(): void
  /** Minimize the native window. */
  minimizeWindow(): void
  /** Run the native zoom or maximize operation. */
  zoomWindow(): void
  /** Enter or exit native fullscreen. */
  toggleFullscreen(): void
  setWindowTitle(title: string): void
  /** Open the platform path picker. Returns null when the user cancels. */
  promptForPaths(options?: PathPromptOptions | undefined | null): Promise<Array<string> | null>
  focusElement(elementId: number): void
  /** Move focus to the next GPUI tab stop. */
  focusNext(): void
  /** Move focus to the previous GPUI tab stop. */
  focusPrevious(): void
  /** Host id of the focused element, or null when nothing is focused. */
  getFocusedElementId(): number | null
  /** Move focus to the next tab stop inside `element_id`, wrapping in that subtree. */
  focusNextWithin(elementId: number): void
  /** Move focus to the previous tab stop inside `element_id`, wrapping in that subtree. */
  focusPreviousWithin(elementId: number): void
  /** Enable the window key events requested by the React renderer. */
  setWindowKeyEvents(keyDown: boolean, keyUp: boolean, eventId: number): void
  blur(): void
  /** Enable the window selectionChange event requested by the React renderer. */
  setWindowSelectionChange(enabled: boolean, eventId: number): void
  /** The current text selection joined in document order, or null. */
  getSelectedText(): string | null
  /** Drop the current selection and request a repaint. */
  clearSelection(): void
  /**
   * Set the scroll offset of a scrollable element.
   * x and y are negative pixel values (scroll down = more negative y).
   */
  scrollTo(elementId: number, x: number, y: number): void
  /**
   * Scroll a child into view by its index in the children list.
   *
   * For a `<virtual-list>` the scroll is queued and applied on the next
   * render, after that frame's child splice, so indices computed against a
   * just-committed child list are never shifted twice. `offsetInItem` is in
   * pixels and may be negative, which anchors the viewport top above the
   * item and resolves against measured heights at layout time.
   */
  scrollToItem(elementId: number, index: number, offsetInItem?: number | undefined | null): void
  /**
   * The logical scroll anchor of a `<virtual-list>`:
   * `[itemIndex, offsetInItemPx, viewportHeightPx]`, or null for anything
   * else. `itemIndex == item count` is gpui's at-end sentinel.
   *
   * Unlike `getScrollOffset` this is exact even while row heights are still
   * estimates, because it is the anchor gpui itself scrolls by.
   */
  getListScrollTop(elementId: number): Array<number> | null
  /**
   * Get the current scroll offset of a scrollable element.
   * Returns [x, y] or null if the element has no scroll handle.
   */
  getScrollOffset(elementId: number): Array<number> | null
  /** Scroll this element's nearest scroll parent until the element is visible. */
  scrollIntoView(elementId: number): void
  /**
   * Paint packed pixels onto an `<img>` host node. `format` is `"rgba"`
   * (default) or `"bgra"`; BGRA skips the per-pixel swizzle.
   */
  setImagePixels(elementId: number, width: number, height: number, pixels: Buffer, format?: string | undefined | null): void
  /**
   * Decode PNG, JPEG, WebP, GIF, SVG, BMP, TIFF, ICO, or Netpbm bytes onto
   * an `<img>` host node. Prefer `setImagePixels` for live waveforms.
   */
  setImage(elementId: number, bytes: Buffer): void
  getAutomationTree(): string
  getElementBounds(id: number): ElementBounds | null
  getAllText(): Array<string>
  getPaintedText(): Array<string>
  /**
   * Every highlight wash painted in the last frame, in paint order.
   *
   * A quad is invisible to `getPaintedText()`, so this is the only way to
   * assert on `highlight` without a screenshot.
   */
  getPaintedHighlights(): Array<HighlightMatch>
  /** Simulate space-separated keystrokes through the focused element's input pipeline. */
  simulateKeystrokes(keystrokes: string): void
  simulateKeyDown(keystroke: string, isHeld?: boolean | undefined | null): void
  simulateKeyUp(keystroke: string): void
  /** `modifiers` uses the `press()` syntax: "cmd", "cmd-shift", "alt". */
  simulateClick(x: number, y: number, button?: number | undefined | null, modifiers?: string | undefined | null): void
  simulateMouseDown(x: number, y: number, button?: number | undefined | null, modifiers?: string | undefined | null): void
  simulateMouseUp(x: number, y: number, button?: number | undefined | null, modifiers?: string | undefined | null): void
  simulateMouseMove(x: number, y: number, pressedButton?: number | undefined | null, modifiers?: string | undefined | null): void
  /**
   * Dispatch a wheel event through the same GPUI hit test the trackpad uses.
   * Deltas are pixels: negative `delta_y` scrolls down, negative `delta_x`
   * pans right, matching `TestGpuixRenderer::simulate_scroll_wheel`.
   */
  simulateScrollWheel(x: number, y: number, deltaX: number, deltaY: number, modifiers?: string | undefined | null): void
  clockPause(): number
  clockSet(nowMs: number): number
  clockFastForward(deltaMs: number): number
  clockResume(): number
  captureScreenshot(path: string): void
}

export declare class TestGpuixRenderer {
  constructor(width?: number | undefined | null, height?: number | undefined | null)
}

/**
 * Ask the update feed whether a newer signed bundle exists.
 *
 * Returns `null` when the feed is 204 or the announced version is not newer.
 * `downloadAndInstall()` replaces the packaged app. It does not relaunch.
 */
export declare function checkUpdate(currentVersion: string, options: CheckUpdateOptions): Promise<AvailableUpdate | null>

/** Options for [`check_update`]. */
export interface CheckUpdateOptions {
  /** Feed URLs. Slots `{{target}}`, `{{arch}}`, `{{current_version}}` are filled. */
  endpoints: Array<string>
  /** Public key from `cargo packager signer generate`. */
  pubkey: string
  /** Extra HTTP headers for the feed request. */
  headers?: Array<UpdaterHeader>
  /** Request timeout in milliseconds. */
  timeoutMs?: number
  /** Windows NSIS / WiX extra args. */
  installerArgs?: Array<string>
  /** Windows install UI: `passive` (default), `quiet`, or `basicUi`. */
  installMode?: string
}

/** Recorded draw times from the debug frame overlay. */
export interface DebugFrameOverlayStats {
  currentMs?: number
  p90Ms?: number
  p99Ms?: number
  maxMs?: number
  frames: number
  samples: number
}

export interface EdgeInsets {
  top: number
  right: number
  bottom: number
  left: number
}

/** Last painted box for a host element. */
export interface ElementBounds {
  x: number
  y: number
  width: number
  height: number
}

export interface EventModifiers {
  shift: boolean
  ctrl: boolean
  alt: boolean
  cmd: boolean
}

/** Event payload sent back to JS when a user interacts with an element. */
export interface EventPayload {
  /** Numeric element ID (matches the ID assigned in JS via createElement). */
  elementId: number
  /**
   * Event type string — matches the key used in EVENT_PROPS on the JS side.
   * e.g. "click", "mouseDown", "mouseEnter", "keyDown", "scroll", etc.
   */
  eventType: string
  /** Mouse X position in window coordinates (pixels). */
  x?: number
  /** Mouse Y position in window coordinates (pixels). */
  y?: number
  /**
   * Which mouse button: 0=left, 1=middle, 2=right.
   * Populated for: mouseDown, mouseUp, click, mouseDownOutside, contextMenu.
   */
  button?: number
  /**
   * Number of consecutive clicks (1=single, 2=double, 3=triple).
   * Populated for: mouseDown, mouseUp, click.
   */
  clickCount?: number
  /**
   * Whether this is a right-click (convenience for click events).
   * true when button==2 or ClickEvent::is_right_click().
   */
  isRightClick?: boolean
  /**
   * Which mouse button is currently held during a mouseMove.
   * Same encoding as `button`: 0=left, 1=middle, 2=right.
   * Populated for: mouseMove.
   */
  pressedButton?: number
  /**
   * Key name, e.g. "a", "enter", "escape", "down", "left", "f1".
   * Populated for: keyDown, keyUp.
   */
  key?: string
  /**
   * The character produced by the key press (e.g. "ß" for option-s).
   * May differ from `key` when modifiers are active.
   * Populated for: keyDown, keyUp.
   */
  keyChar?: string
  /**
   * Whether this is a key-repeat event (key held down).
   * Populated for: keyDown.
   */
  isHeld?: boolean
  /**
   * Id of the GPUI key dispatch that produced this event. Every element
   * `keyDown` and the trailing `windowKeyDown` of one keystroke share it, so
   * JS can apply `preventDefault` / `stopPropagation` across them.
   * Populated for: keyDown, keyUp, windowKeyDown, windowKeyUp.
   */
  keystrokeId?: number
  /**
   * Scroll delta on the X axis (pixels or lines, see `precise`).
   * Populated for: scroll.
   */
  deltaX?: number
  /**
   * Scroll delta on the Y axis (pixels or lines, see `precise`).
   * Populated for: scroll.
   */
  deltaY?: number
  /**
   * true = pixel-precise (trackpad), false = line-based (mouse wheel).
   * Populated for: scroll.
   */
  precise?: boolean
  /**
   * Touch phase for scroll: "started", "moved", "ended".
   * Populated for: scroll (trackpad gestures).
   */
  touchPhase?: string
  /**
   * true = mouse entered element, false = mouse left element.
   * Populated for: mouseEnter, mouseLeave.
   */
  hovered?: boolean
  /**
   * Element-defined string payload.
   * Populated for: `<diff>` toggleFile (the file path), showMore (the
   * hidden line count), and lineClick (the line text); `<markdown>`
   * linkClick (the URL); `selectionChange` (joined selected text, or
   * absent when the selection is empty).
   */
  value?: string
  /** Line number on the pre-change side. Populated for: `<diff>` lineClick. */
  oldLine?: number
  /** Line number on the post-change side. Populated for: `<diff>` lineClick. */
  newLine?: number
  /** First visible logical index. Populated for: `<virtual-list>` visibleRange. */
  startIndex?: number
  /** Exclusive end of the visible logical range. Populated for: visibleRange. */
  endIndex?: number
  /**
   * Matches found by this element's `highlight` prop. Counted once per match
   * even when it is split across several painted runs, and it counts every
   * retained match, not only the ones currently on screen.
   * Populated for: highlight.
   */
  matchCount?: number
  /**
   * Logical native motion target that reached completion.
   * Populated for: motionComplete.
   */
  motionGeneration?: number
  /**
   * Absolute filesystem paths from a Finder / OS file drop.
   * Populated for: fileDrop.
   */
  paths?: Array<string>
  modifiers?: EventModifiers
}

/** True only when this binary compiled the real GPU test renderer. */
export declare function hasTestGpuixRenderer(): boolean

/**
 * One highlight wash painted in the last frame, with the boxes it drew.
 *
 * The rects matter: a quad never lands in `getPaintedText()`, and a match that
 * soft-wraps must produce one box per visual row. Without the geometry the only
 * way to assert either is a screenshot.
 */
export interface HighlightMatch {
  /** Numeric id of the element that painted the run. */
  elementId: number
  /** Index of the run within that element. 0 for a plain `<text>`. */
  sub: number
  /** The full string of the run, so `text.slice(start, end)` is the match. */
  text: string
  /** UTF-16 code-unit offsets into `text`, the units JS strings use. */
  start: number
  end: number
  active: boolean
  rects: Array<HighlightRect>
}

export interface HighlightRect {
  x: number
  y: number
  width: number
  height: number
}

/** A code block for JavaScript to highlight; see [`GpuixRenderer::on_highlight`]. */
export interface HighlightRequest {
  id: number
  code: string
  /** The Markdown fence tag or `<code>` language, as written. */
  language?: string
  path?: string
}

/**
 * Wayland `wlr-layer-shell` surface options. Linux/Wayland only; ignored on
 * every other platform. When present on `WindowOptions`, the window is opened
 * as a compositor-anchored surface (a bar, dock, notification overlay or
 * wallpaper) with no native titlebar instead of a normal floating window.
 * `width` / `height` then only constrain the axis the surface is not
 * stretched along by its `anchor`.
 */
export interface LayerShellOptions {
  /**
   * Compositor surface namespace, used for window rules. Cannot be changed
   * after the surface is created. Defaults to the empty string.
   */
  namespace?: string
  /** `"background"` | `"bottom"` | `"top"` | `"overlay"`. Defaults to `"top"`. */
  layer?: string
  /**
   * Screen edges to anchor to: any combination of `"top"`, `"bottom"`,
   * `"left"`, `"right"`. Anchoring two opposite edges stretches the surface
   * across that axis. Defaults to `["top", "left", "right"]` (a top bar).
   */
  anchor?: Array<string>
  /**
   * Logical pixels to reserve along the anchored edge so other windows do
   * not overlap the surface. `0` lets the compositor decide, a negative
   * value asks it not to reserve any space.
   */
  exclusiveZone?: number
  /**
   * Which edge the exclusive zone applies to when it cannot be inferred from
   * a single-edge `anchor`. Same values as one `anchor` entry.
   */
  exclusiveEdge?: string
  /**
   * Gap between the surface and its anchor edge(s), in CSS order:
   * `[top, right, bottom, left]`. Must have exactly four entries or it is
   * ignored.
   */
  margin?: Array<number>
  /**
   * `"none"` | `"on-demand"` | `"exclusive"`. Defaults to `"none"`: a bar or
   * overlay that never takes keyboard focus.
   */
  keyboardInteractivity?: string
}

export interface PathPromptOptions {
  /** Select files. Defaults to true unless `directories` is true. */
  files?: boolean
  /** Select directories. Defaults to false. */
  directories?: boolean
  /** Allow several paths. Defaults to false. */
  multiple?: boolean
  /** Label for the picker confirmation button. */
  prompt?: string
}

/** One extra HTTP header on the feed or download request. */
export interface UpdaterHeader {
  name: string
  value: string
}

export interface WindowInsets {
  safeArea: EdgeInsets
  ime: EdgeInsets
  effective: EdgeInsets
}

export interface WindowOptions {
  title?: string
  /**
   * The name used inside the macOS "Hide" and "Quit" menu items. Defaults to
   * `title`. It does NOT set the title of the application menu itself: macOS
   * takes that from the executable, and only a `.app` bundle changes it.
   */
  appName?: string
  width?: number
  height?: number
  minWidth?: number
  minHeight?: number
  resizable?: boolean
  fullscreen?: boolean
  /** Plain alpha transparency. Prefer `window_background` when you need blur. */
  transparent?: boolean
  /** Hide the native titlebar so the app can draw chrome under the traffic lights. */
  titlebarTransparent?: boolean
  /**
   * Let the app draw the whole window, title bar included. Mark its regions
   * with `<gpuix-caption>` so dragging and the caption buttons stay native.
   */
  clientDecorations?: boolean
  /**
   * Font files to load before the window opens, so styles can name their
   * families without the fonts being installed.
   */
  fonts?: Array<string>
  /**
   * Decoded `<img>` files and URLs kept in memory while off screen, in MB.
   * Defaults to 256; the least recently drawn go first.
   */
  imageMemoryMb?: number
  /**
   * `"opaque"` | `"transparent"` | `"blurred"`. `transparent: true` is the
   * same as `"transparent"` when this is unset.
   */
  windowBackground?: string
  trafficLightX?: number
  trafficLightY?: number
  /**
   * Give the window key focus when it opens. `false` opens it behind the
   * active app, like `open -g`. Ignored on Linux.
   */
  focus?: boolean
  /**
   * Show the window when it opens. `false` opens it hidden; call
   * `activateWindow()` to reveal it. Ignored on Linux.
   */
  show?: boolean
  /**
   * Application id: Wayland `app_id` / X11 `WM_CLASS`. Desktop environments
   * use it to group windows and match window rules. Required in practice for
   * a `layerShell` surface a compositor is meant to target by rule.
   */
  appId?: string
  /**
   * Open the window as a Wayland `wlr-layer-shell` surface instead of a
   * normal window. Linux/Wayland only; ignored elsewhere.
   */
  layerShell?: LayerShellOptions
}

export interface WindowSize {
  width: number
  height: number
}

export interface WindowState {
  closed: boolean
  maximized: boolean
  fullscreen: boolean
  /** Whether this is the foreground window; native caption glyphs dim when not. */
  active: boolean
  /** The system appearance, for themes that follow it. */
  dark: boolean
  width: number
  height: number
}
